### ISSUE TITLE
TaskError - taskid:render_taxonomies:output/archive.html ... lxml.etree.ParserError: Document is empty

### ISSUE THREAD

**Issue by uogbuji** [getnikola/nikola#3507]
### Environment

**Python Version:** 3.8.5

**Nikola Version:** v8.1.2

**Operating System:** Mac Catalina

### Description:

A site (pages only, no blog) that's been working for years on Nikola all of a sudden fails `nikola build`.

First I ran into:

```
$ nikola build
Scanning posts....done!
.  copy_files:output/feeds/vanity.versa.md
.  copy_files:output/img/BlackSpringBooksellerAdvert-justuogbuji.png
.  copy_files:output/img/BlackSpringBooksellerAdvert.jpg
.  render_taxonomies:output/archive.html
TaskError - taskid:render_taxonomies:output/archive.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/uche/.local/venv/main/lib/python3.8/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/uche/.local/venv/main/lib/python3.8/site-packages/nikola/nikola.py", line 1493, in render_template
    doc = lxml.html.document_fromstring(data.strip(), parser)
  File "/Users/uche/.local/venv/main/lib/python3.8/site-packages/lxml/html/__init__.py", line 763, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

########################################
render_taxonomies:output/archive.html <stdout>:
```

After a little googling tried removing POSTS = {} from conf.py. It now does a lot more before failing with the same error.

```
nikola build   
Scanning posts...done!
.  copy_assets:output/assets/css/custom.css
.  copy_assets:output/assets/js/jssor.slider.min.js
.  copy_assets:output/assets/js/jquery-3.1.1.min.js
.  copy_assets:output/assets/js/NOTES.md
.  copy_assets:output/assets/css/bootstrap.min.css
.  copy_assets:output/assets/css/bootstrap.css
.  copy_assets:output/assets/css/theme.css
.  copy_assets:output/assets/css/colorbox.css
.  copy_assets:output/assets/css/bootstrap-glyphicons.css
.  copy_assets:output/assets/css/bootstrap-theme.css
.  copy_assets:output/assets/css/docs.css
.  copy_assets:output/assets/css/bootstrap-theme.min.css
.  copy_assets:output/assets/css/images/ie6/borderBottomLeft.png
.  copy_assets:output/assets/css/images/ie6/borderTopRight.png
.  copy_assets:output/assets/css/images/ie6/borderMiddleLeft.png
.  copy_assets:output/assets/css/images/ie6/borderTopCenter.png
.  copy_assets:output/assets/css/images/ie6/borderMiddleRight.png
.  copy_assets:output/assets/css/images/ie6/borderBottomCenter.png
.  copy_assets:output/assets/css/images/ie6/borderBottomRight.png
.  copy_assets:output/assets/css/images/ie6/borderTopLeft.png
.  copy_assets:output/assets/js/bootstrap.js
.  copy_assets:output/assets/js/bootstrap.min.js
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.woff
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.eot
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.ttf
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.svg
.  copy_assets:output/assets/css/bootstrap-responsive.css
.  copy_assets:output/assets/css/bootstrap-responsive.min.css
.  copy_assets:output/assets/css/images/border.png
.  copy_assets:output/assets/css/images/loading.gif
.  copy_assets:output/assets/css/images/overlay.png
.  copy_assets:output/assets/css/images/controls.png
.  copy_assets:output/assets/css/images/loading_background.png
.  copy_assets:output/assets/js/jquery.colorbox-min.js
.  copy_assets:output/assets/js/flowr.plugin.js
.  copy_assets:output/assets/js/jquery-1.10.2.min.js
.  copy_assets:output/assets/js/imagesloaded.pkgd.min.js
.  copy_assets:output/assets/img/glyphicons-halflings.png
.  copy_assets:output/assets/img/glyphicons-halflings-white.png
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/js/mathjax.js
.  copy_assets:output/assets/css/nikola_rst.css
.  copy_assets:output/assets/css/nikola_ipython.css
.  copy_assets:output/assets/css/html4css1.css
.  copy_assets:output/assets/css/ipython.min.css
.  copy_assets:output/assets/css/rst_base.css
.  copy_assets:output/assets/css/baguetteBox.min.css
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/js/gallery.min.js
.  copy_assets:output/assets/js/fancydates.min.js
.  copy_assets:output/assets/js/gallery.js
.  copy_assets:output/assets/js/baguetteBox.min.js
.  copy_assets:output/assets/js/html5shiv-printshiv.min.js
.  copy_assets:output/assets/js/justified-layout.min.js
.  copy_assets:output/assets/js/luxon.min.js
.  copy_assets:output/assets/xml/atom.xsl
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/css/code.css
.  copy_files:output/robots.txt
.  copy_files:output/poetry-voice-podcast.xml
.  copy_files:output/etc/tech/index.txt
.  copy_files:output/etc/tech/python/index.txt
.  copy_files:output/etc/tech/publications/index.txt
.  copy_files:output/etc/tech/articles/FtSuiteWiki_2fUserNotes.html
.  copy_files:output/etc/tech/articles/4xslt.pdf
.  copy_files:output/etc/tech/articles/tr308.pdf
.  copy_files:output/etc/tech/articles/ws-metadata.html
.  copy_files:output/etc/tech/articles/xmledi.html
.  copy_files:output/etc/tech/articles/ws-metadata.css
.  copy_files:output/etc/tech/articles/schematron.xhtml
.  copy_files:output/etc/tech/articles/schematron.html
.  copy_files:output/etc/tech/articles/svgpres.html
.  copy_files:output/etc/tech/articles/oop-ll.pdf
.  copy_files:output/etc/tech/articles/xml-europe-2002.pdf
.  copy_files:output/etc/tech/articles/svgpres.xhtml
.  copy_files:output/etc/tech/articles/bulging-std.html
.  copy_files:output/etc/tech/articles/rdfws-paper.doc
.  copy_files:output/etc/tech/articles/whatarews.xhtml
.  copy_files:output/etc/tech/articles/xmledi.xhtml
.  copy_files:output/etc/tech/articles/x-4suite5-ltr.pdf
.  copy_files:output/etc/tech/articles/past_present_future.pdf
.  copy_files:output/etc/tech/articles/images/xmlj-mag-logo-145.gif
.  copy_files:output/etc/tech/articles/images/ogbuji01_01.gif
.  copy_files:output/etc/tech/articles/images/rdf-eg.png
.  copy_files:output/etc/tech/articles/images/T.gif
.  copy_files:output/etc/tech/articles/images/W.gif
.  copy_files:output/etc/tech/articles/images/a-ogbuji.jpg
.  copy_files:output/etc/tech/articles/images/swol-1020-svg_fig1_sml.gif
.  copy_files:output/etc/tech/articles/images/spacer.gif
.  copy_files:output/etc/tech/articles/images/N.gif
.  copy_files:output/etc/tech/articles/images/X.gif
.  copy_files:output/etc/tech/articles/images/swol-1020-svg_fig2_sml.gif
.  copy_files:output/etc/tech/articles/images/swol-1020-svg_fig2.gif
.  copy_files:output/etc/tech/articles/images/swol-1020-svg_fig1.gif
.  copy_files:output/etc/tech/rdf/index.txt
.  copy_files:output/etc/tech/rdf/versa/versa-1.0.txt
.  copy_files:output/etc/tech/rdf/versa/index.txt
.  copy_files:output/etc/tech/rdf/versa/versa-by-example.txt
.  copy_files:output/etc/tech/rdf/versa/etc/Maycotte-overview.pdf
.  copy_files:output/etc/tech/rdf/versa/etc/Maycotte-rdfapp.tar.gz
.  copy_files:output/etc/tech/rdf/versa/etc/wordnet.rdf
.  copy_files:output/etc/tech/rdf/versa/etc/versa-1.0.xml
.  copy_files:output/etc/tech/rdf/versa/etc/ogbuji.rdf
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example.zip
.  copy_files:output/etc/tech/rdf/versa/etc/Maycotte-rdfposter.pdf
.  copy_files:output/etc/tech/rdf/versa/etc/Maycotte-rdfarticle.pdf
.  copy_files:output/etc/tech/rdf/versa/etc/Maycotte.pdf
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/old-wordnet.gif
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/wordnet.rdf
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/ogbuji.rdf
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/README
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/wordnet.jpg
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/versa-by-example.txt
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/ogbuji.jpg
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/query-files/q8.versa
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/query-files/q9.versa
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/query-files/q10.versa
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/query-files/q3.versa
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/query-files/q7.versa
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/query-files/q5.versa
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/query-files/q2.versa
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/query-files/q4.versa
.  copy_files:output/etc/tech/rdf/versa/etc/versa-by-example/query-files/q6.versa
.  copy_files:output/etc/tech/4suite/index.txt
.  copy_files:output/etc/tech/4suite/anobind/index.txt
.  copy_files:output/etc/tech/4suite/etc/Amara-1.0.zip
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.9.zip
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.7-allinone.tar.gz
.  copy_files:output/etc/tech/4suite/etc/Amara-1.0.tar.bz2
.  copy_files:output/etc/tech/4suite/etc/add-nsmapping.py
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.6.tar.bz2
.  copy_files:output/etc/tech/4suite/etc/add-xslt-strobe.py
.  copy_files:output/etc/tech/4suite/etc/update-xslt-api.py
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.7.tar.bz2
.  copy_files:output/etc/tech/4suite/etc/4ODS-userguide.doc
.  copy_files:output/etc/tech/4suite/etc/4ODS-userguide.html
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.7-allinone.zip
.  copy_files:output/etc/tech/4suite/etc/config-helper.xslt
.  copy_files:output/etc/tech/4suite/etc/create-nsmapping-file.py
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.6.tar.gz
.  copy_files:output/etc/tech/4suite/etc/Amara-docs-1.1.9.zip
.  copy_files:output/etc/tech/4suite/etc/Amara-docs-1.1.9.tar.gz
.  copy_files:output/etc/tech/4suite/etc/Amara-1.0.tar.gz
.  copy_files:output/etc/tech/4suite/etc/helper.xslt
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.7-allinone.tar.bz2
.  copy_files:output/etc/tech/4suite/etc/docbook_html.css
.  copy_files:output/etc/tech/4suite/etc/Amara-docs-1.1.9.tar.bz2
.  copy_files:output/etc/tech/4suite/etc/amara-manual.html
.  copy_files:output/etc/tech/4suite/etc/sdocbook_html.css
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.9.tar.bz2
.  copy_files:output/etc/tech/4suite/etc/Amara-1.2a2.zip
.  copy_files:output/etc/tech/4suite/etc/CoreManual.html
.  copy_files:output/etc/tech/4suite/etc/4Suite-cc.rdf
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.9.tar.gz
.  copy_files:output/etc/tech/4suite/etc/Triclops.xslt
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.6.zip
.  copy_files:output/etc/tech/4suite/etc/Amara-1.2a2.tar.gz
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.7.tar.gz
.  copy_files:output/etc/tech/4suite/etc/Amara-1.2a2.tar.bz2
.  copy_files:output/etc/tech/4suite/etc/Amara-1.1.7.zip
.  copy_files:output/etc/tech/4suite/etc/scratch-server.py
.  copy_files:output/etc/tech/4suite/scimitar/index.txt
.  copy_files:output/etc/tech/4suite/amara/index.txt
.  copy_files:output/etc/tech/4suite/amara/manual-dev.txt
.  copy_files:output/etc/tech/4suite/amara/quickref.txt
.  copy_files:output/etc/tech/4suite/amara/manual.txt
.  copy_files:output/etc/tech/4suite/ibmdw-tutorial/index.txt
.  copy_files:output/etc/tech/4suite/akara/index.txt
.  copy_files:output/etc/tech/4suite/wsgixml/index.txt
.  copy_files:output/feeds/poetry.atom
.  copy_files:output/feeds/vanity.versa.md
.  copy_files:output/feeds/publications.md
.  copy_files:output/feeds/publications.atom
.  copy_files:output/feeds/poetry.versa.md
.  copy_files:output/img/psf.jpg
.  copy_files:output/img/Uche-by-Hedman.jpg
.  copy_files:output/img/cba2014logo_transparent.png
.  copy_files:output/img/microxml-logo.png
.  copy_files:output/img/ColoradoPoetrySquarish-tiny.png
.  copy_files:output/img/libhub-logo.png
.  copy_files:output/img/NdewoColoradoPlate.jpg
.  copy_files:output/img/BlackSpringBooksellerAdvert-justuogbuji.png
.  copy_files:output/img/akara.png
.  copy_files:output/img/BlackSpringBooksellerAdvert.jpg
.  copy_files:output/img/akara-blackhand.png
.  copy_files:output/img/litgallery/twovoicedflute.png
.  copy_files:output/img/litgallery/furiesofmadmax.png
.  copy_files:output/img/litgallery/follybetween.jpg
.  copy_files:output/img/litgallery/westernborderincident.png
.  copy_files:output/img/litgallery/nighthike.png
.  copy_files:output/img/litgallery/poetryvoice-dayofthedead.png
.  copy_files:output/img/litgallery/poetryvoice-dayofthedead-opt.png
.  copy_files:output/img/litgallery/trackcouture.png
.  copy_files:output/img/litgallery/follybetween-opt.jpg
.  copy_files:output/img/litgallery/westernborderincident-opt.png
.  copy_files:output/img/litgallery/twovoicedflute-opt.png
.  copy_files:output/img/litgallery/NOTES.md
.  copy_files:output/img/litgallery/juliansbloodmoon.png
.  copy_files:output/img/litgallery/furiesofmadmax-opt.png
.  copy_files:output/img/ndewogallery/unsprung.png
.  copy_files:output/img/ndewogallery/catamount.jpg
.  copy_files:output/img/ndewogallery/endo.png
.  copy_files:output/img/ndewogallery/NOTES.md
.  copy_files:output/img/tech/laptopdemo.jpg
.  copy_files:output/mavodata/README.md
.  render_sources:output/nchefu/index.md
.  render_sources:output/lit/index.md
.  render_sources:output/tech/index.md
.  render_sources:output/lit/rhymefriendly/rhymefriendly/index.md
.  render_sources:output/poetryvoice/index.md
.  render_sources:output/ndewo/index.md
.  render_sources:output/index.md
.  render_taxonomies:output/blog/index.html
.  render_taxonomies:output/archive.html
TaskError - taskid:render_taxonomies:output/archive.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/uche/.local/venv/main/lib/python3.8/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/uche/.local/venv/main/lib/python3.8/site-packages/nikola/nikola.py", line 1493, in render_template
    doc = lxml.html.document_fromstring(data.strip(), parser)
  File "/Users/uche/.local/venv/main/lib/python3.8/site-packages/lxml/html/__init__.py", line 763, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

########################################
render_taxonomies:output/archive.html <stdout>:
```

Now I'm stuck.

**Comment by Kwpolska** [comment]
@uogbuji Is the source of your site available anywhere?

**Comment by uogbuji** [comment]
@Kwpolska sorry, not sure why I didn't get notifications. See: https://github.com/uogbuji/uche.ogbuji.net

**Comment by aquinzi** [comment]
I confirm. I just updated Nikola from v7.x.x.x. (I guess) to the lastest, also a site without blog, and it fails with the same error and the same file (`render_taxonomies:_output/blog/archive.html`) . It also randomly happens in other (to be generated-) files, but this can be because I'm still migrating from an old version.

Environment:
Python Version: 3.8.5
Nikola Version: v8.1.2
Operating System: Linux Mint 20

**Comment by uogbuji** [comment]
@aquinzi do you happen to remember what version you migrated from? I want to revert to the newest release that doesn't have this bug. Thanks!

**Comment by Kwpolska** [comment]
@uogbuji I checked your site, you have outdated copies of Nikola base themes. Copying `base-jinja` into `themes` can lead to unexpected results and breakage like this. To fix your site, run:

```
git rm -rf themes/{base-jinja,bootstrap-jinja,bootstrap3-jinja}
nikola theme -i bootstrap3-jinja
```

Afterwards, your site will work with Nikola v8.1.2+.

**Comment by Kwpolska** [comment]
@aquinzi If your blog is at https://github.com/aquinzi/quinzi-blog , the same issue with a disallowed custom copy of `base-jinja` applies. (I can’t get your site to build due to missing files and other configuration, the repo wasn’t updated since 2016 so I guess some of those got fixed in the meantime/as part of other compatibility work).

@uogbuji @aquinzi To customize Nikola-provided templates, make copies of *specific* templates in your own theme or in the `templates` directory. To do this, you can use `nikola theme -c foo.tmpl`, which will copy `foo.tmpl` to either `templates` or `themes/$THEME` (depending on theme availability).

**Comment by uogbuji** [comment]
Thanks @Kwpolska . I don't recall ever doing anything with themes that didn't come straight form the docs, but then again I haven't done anything at all with themes in probably a few years.

Anyway, I followed your instructions:

```
(main) ➜  uche.ogbuji.net git:(master) git rm -rf themes/{base-jinja,bootstrap-jinja,bootstrap3-jinja}
[SNIP]
(main) ➜  uche.ogbuji.net git:(master) ✗ nikola theme -i bootstrap3-jinja
[2021-02-06 12:33:20] WARNING: Nikola: Cannot load theme "ndewotime", using 'bootblog4' instead.
[2021-02-06 12:33:20] INFO: theme: Downloading 'https://themes.getnikola.com/v8/bootstrap3-jinja.zip'
[2021-02-06 12:33:21] INFO: theme: Extracting 'bootstrap3-jinja' into themes/
[2021-02-06 12:33:21] INFO: theme: Remember to set THEME="bootstrap3-jinja" in conf.py to use this theme.
(main) ➜  uche.ogbuji.net git:(master) ✗ 
```

Notice the warning on my custom theme "ndewotime", but as you say, `nikola build` works fine after that, and the theme looks fine to my eyeballs, so I **think** I'm good now. Thanks again!

**Comment by Kwpolska** [comment]
@uogbuji The warning was expected at this point, because you removed `bootstrap3-jinja`, on which `ndewotime` depends. It shouldn’t appear in future builds.

**Comment by aquinzi** [comment]
Yes @Kwpolska I think that was the problem. An outdated theme (in my case `jinja-base`) was causing the issue. Thank you!

**Comment by gipi** [comment]
I have the same problem, my blog stopped working with a similar error

```
2022-08-26T11:03:45.5281077Z .  render_taxonomies:output/categories/browser/index.html
2022-08-26T11:03:45.5340052Z .  render_taxonomies:output/2020/08/25/index.html
2022-08-26T11:03:45.5397610Z .  render_taxonomies:output/2020/08/index.html
2022-08-26T11:03:45.5447721Z .  render_taxonomies:output/2020/07/index.html
2022-08-26T11:03:45.5495869Z .  render_taxonomies:output/index.html
2022-08-26T11:03:46.1048513Z TaskError - taskid:render_taxonomies:output/index.html
2022-08-26T11:03:46.1098672Z PythonAction Error
2022-08-26T11:03:46.1099234Z Traceback (most recent call last):
2022-08-26T11:03:46.1108214Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/doit/action.py", line 461, in execute
2022-08-26T11:03:46.1108734Z     returned_value = self.py_callable(*self.args, **kwargs)
2022-08-26T11:03:46.1109481Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nikola/nikola.py", line 1487, in render_template
2022-08-26T11:03:46.1109910Z     data = self.template_system.render_template(
2022-08-26T11:03:46.1110588Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nikola/plugins/template/mako.py", line 118, in render_template
2022-08-26T11:03:46.1111036Z     data = template.render_unicode(**context)
2022-08-26T11:03:46.1111650Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mako/template.py", line 444, in render_unicode
2022-08-26T11:03:46.1112250Z     return runtime._render(
2022-08-26T11:03:46.1112886Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mako/runtime.py", line 874, in _render
2022-08-26T11:03:46.1113259Z     _render_context(
2022-08-26T11:03:46.1114117Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mako/runtime.py", line 916, in _render_context
2022-08-26T11:03:46.1114587Z     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
2022-08-26T11:03:46.1115243Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mako/runtime.py", line 943, in _exec_template
2022-08-26T11:03:46.1115642Z     callable_(context, *args, **kwargs)
2022-08-26T11:03:46.1116044Z   File "/home/runner/work/blog/blog/cache/.mako.tmp/base.tmpl.py", line 102, in render_body
2022-08-26T11:03:46.1116475Z     context['self'].content(**pageargs)
2022-08-26T11:03:46.1116911Z   File "/home/runner/work/blog/blog/cache/.mako.tmp/index.tmpl.py", line 203, in render_content
2022-08-26T11:03:46.1117318Z     __M_writer(str(post.text(teaser_only=True)))
2022-08-26T11:03:46.1117912Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nikola/post.py", line 929, in text
2022-08-26T11:03:46.1118408Z     min_remaining_read=self.messages[lang]["%d min remaining to read"] % (self.remaining_reading_time),
2022-08-26T11:03:46.1119119Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nikola/post.py", line 977, in remaining_reading_time
2022-08-26T11:03:46.1119548Z     text = self.text(teaser_only=True, strip_html=True)
2022-08-26T11:03:46.1120127Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/nikola/post.py", line 936, in text
2022-08-26T11:03:46.1120533Z     document = lxml.html.fromstring(teaser)
2022-08-26T11:03:46.1121138Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/lxml/html/__init__.py", line 873, in fromstring
2022-08-26T11:03:46.1121588Z     doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
2022-08-26T11:03:46.1122293Z   File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
2022-08-26T11:03:46.1122715Z     raise etree.ParserError(
2022-08-26T11:03:46.1123018Z lxml.etree.ParserError: Document is empty
2022-08-26T11:03:46.1123210Z 
2022-08-26T11:03:46.1177981Z ########################################
2022-08-26T11:03:46.1273883Z render_taxonomies:output/index.html <stdout>:
2022-08-26T11:03:46.2064871Z '<p>This post is going to be too ambitious probably: 
```

I have a folder with the ``zen`` theme but also removing and using the pristine version doesn't fix the error.

My blog is [here](https://github.com/gipi/blog), and there is an automatic Github action to build the pages, so you can check also there.

**Note:** if I do ``nikola serve`` it hangs, as indicated in #3638

**Comment by gipi** [comment]
Update: it seems that having a ``<!-- TEASER_END -->`` just at the start of a post it's causing that, if I move it in order to contains some text to show in the preview of in the index page then it builds correctly. Also ``nikola auto`` now doesn't hang (sorry I indicated the wrong command in the previous comment).

**Comment by ralsina** [comment]
Good catch! Yeah, a teaser with nothing in it does break things. It's not a
very hard fix if you want to take a shot :-D

**Comment by gipi** [comment]
I can take a look at it the next week, however this is a regression because started happening when I updated ``nikola`` so I would appreciate some guidance on where to look for the fix ^_^

**Comment by ralsina** [comment]
I think it's just a missing try/except here and if it fails because the
document is empty, make doc an empty string:

File "/Users/uche/.local/venv/main/lib/python3.8/site-packages/nikola/nikola.py",
line 1493, in render_template
    doc = lxml.html.document_fromstring(data.strip(), parser)
